use std::collections::HashMap;

/// # Body
/// 
/// Any 'static' body of the game. Asteroids, planets, moons, even stars.
/// 
/// This does not include orbital data, just the phsyical properties of the body, 
/// including material data.
#[derive(Debug, Clone)]
pub struct Body {
    /// The Unique ID of the body.
    pub id: usize,
    /// The name of the planet. Randomly Generated by system, editable by player.
    pub name: String,

    /// The type of body the planet is. Used primarily for information and during
    /// generation. Can update upon some various events, such as the transitioning from
    /// gas planet to Chthonian.
    pub body_type: BodyType,

    /// The mass of the object, should also be used by the orbital objects.
    pub total_mass: f64,
    /// The resources which exist on the planet that have not been tapped.
    /// Broken down by id of the resource.
    pub resources: HashMap<usize, f64>,

    /// Things that have been put/stored on the planet by the player. Trivially
    /// accessable, but does not modify mass of the planet.
    pub storage: HashMap<usize, f64>,

    /// The radius of the planet, measured in meters.
    pub radius: f64,

    /// The tempurature of the body.
    /// This is calculated from the energy input by the star (unless it is the star,
    /// in which case it is the surface tempurature of the star).
    pub tempurature: f64,

    // TODO: Put player buildings/components here.
}

/// The available planet types in the game. Currently fixed to this list, may become
/// moddable later.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BodyType {
    /// Earth like planet. Habitable. Good balance of resources.
    Terran,
    /// Similar to terrestrial, but heavy on organics.
    Acidic,
    /// Uninhabitable, tends to be metal heavy.
    Terrestrial,
    /// Uninhabitable, tends to be organic and hydrogen heavy.
    Icy,
    /// Gas planet, mostly hydrogen with a Chthonian Core.
    Jovian,
    /// Gas planet, cold and icy. Lots of hydrogen and Organics with a Chthonian Core.
    Neptunian,
    /// The remnant of a Gas planent, not normally generated.
    Chthonian,
    /// Small body, Hydrogen and Organic poor, but structural, Lightweight, and 
    /// technologically heavy.
    MetallicAsteroid,
    /// Small body, organic heavy.
    CarboniferousAsteroid,
    /// Small body, structural metal heavy, with a decent amount of organics.
    SiliceousAsteroid,
    /// Small body, extreme orbits, Lost of Hydrogen and Organics.
    Comet,
    /// Center body, produces heat for the rest of the center
    /// 
    /// There should only be one, at least for now.
    Star,
}